tap "homebrew/bundle"
tap "homebrew/cask-fonts"
brew "autojump"
brew "cask"
brew "cocoapods"
brew "curl"
brew "fd"
brew "fzf"
brew "gnupg"
brew "jq"
brew "lsd"
brew "mas"
brew "neovim"
brew "pinentry-mac"
brew "zsh"
brew "zsh-syntax-highlighting"
cask "android-sdk"
cask "arc"
cask "flutter"
cask "font-hack-nerd-font"
cask "font-monaspace"
cask "google-chrome"
cask "iterm2"
cask "jetbrains-toolbox"
cask "logi-options-plus"
cask "miniconda"
cask "notion"
cask "orbstack"
cask "raycast"
mas "MindNode", id: 1289197285
mas "RunCat", id: 1429033973
mas "Xcode", id: 497799835
